/**
 * The USS property names Unity 6.3 LTS (6000.3) accepts, transcribed from the
 * manual's USS properties reference. A name outside this set is dropped by
 * Unity's style sheet importer, so the editor reports it rather than letting it
 * look applied.
 */
const UNITY_USS_PROPERTIES: ReadonlySet<string> = new Set([
  '-unity-background-image-tint-color',
  '-unity-background-scale-mode',
  '-unity-editor-text-rendering-mode',
  '-unity-font',
  '-unity-font-definition',
  '-unity-font-style',
  '-unity-material',
  '-unity-overflow-clip-box',
  '-unity-paragraph-spacing',
  '-unity-slice-bottom',
  '-unity-slice-left',
  '-unity-slice-right',
  '-unity-slice-scale',
  '-unity-slice-top',
  '-unity-slice-type',
  '-unity-text-align',
  '-unity-text-auto-size',
  '-unity-text-generator',
  '-unity-text-outline',
  '-unity-text-outline-color',
  '-unity-text-outline-width',
  '-unity-text-overflow-position',
  'align-content',
  'align-items',
  'align-self',
  'all',
  'aspect-ratio',
  'background-color',
  'background-image',
  'background-position',
  'background-position-x',
  'background-position-y',
  'background-repeat',
  'background-size',
  'border-bottom-color',
  'border-bottom-left-radius',
  'border-bottom-right-radius',
  'border-bottom-width',
  'border-color',
  'border-left-color',
  'border-left-width',
  'border-radius',
  'border-right-color',
  'border-right-width',
  'border-top-color',
  'border-top-left-radius',
  'border-top-right-radius',
  'border-top-width',
  'border-width',
  'bottom',
  'color',
  'cursor',
  'display',
  'filter',
  'flex',
  'flex-basis',
  'flex-direction',
  'flex-grow',
  'flex-shrink',
  'flex-wrap',
  'font-size',
  'height',
  'justify-content',
  'left',
  'letter-spacing',
  'margin',
  'margin-bottom',
  'margin-left',
  'margin-right',
  'margin-top',
  'max-height',
  'max-width',
  'min-height',
  'min-width',
  'opacity',
  'overflow',
  'padding',
  'padding-bottom',
  'padding-left',
  'padding-right',
  'padding-top',
  'position',
  'right',
  'rotate',
  'scale',
  'text-overflow',
  'text-shadow',
  'top',
  'transform-origin',
  'transition',
  'transition-delay',
  'transition-duration',
  'transition-property',
  'transition-timing-function',
  'translate',
  'visibility',
  'white-space',
  'width',
  'word-spacing',
]);

export function unityUssPropertyNames(): readonly string[] {
  return Object.freeze([...UNITY_USS_PROPERTIES].sort());
}

/** Custom properties are author-defined, so any `--name` is known by definition. */
export function isCustomUssProperty(property: string): boolean {
  return property.startsWith('--');
}

export function isKnownUssProperty(property: string): boolean {
  return isCustomUssProperty(property) || UNITY_USS_PROPERTIES.has(property);
}
